# Generated by Django 3.1.4 on 2021-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='ArmyExam',
        ),
    ]
