# Generated by Django 3.1.4 on 2021-07-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_armyexam_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armyexam',
            old_name='modeofexam',
            new_name='mode_of_exam',
        ),
    ]
