# Generated by Django 3.1.4 on 2021-07-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_navyexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirforceExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=50)),
                ('occurance', models.CharField(max_length=50)),
                ('mode_of_exam', models.CharField(max_length=50)),
                ('eligibility_nationality', models.CharField(max_length=10000)),
                ('eligibility_educational', models.CharField(max_length=10000)),
                ('eligibility_age', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
